### ISSUE TITLE
Dark-theme doesn't work in 2.346.1

### ISSUE THREAD

**Issue by webminster** [jenkinsci/dark-theme-plugin#210] opened 2022-06-27 22:49 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.346.1
OS: Linux - 5.4.0-1080-aws
---
ace-editor:1.1
amazon-ecr:1.73.v741d474abe74
ansicolor:1.0.1
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
aws-codebuild:0.57
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-cloudformation:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-codebuild:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ec2:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ecr:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ecs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-elasticbeanstalk:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-iam:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-logs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-minimal:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-sns:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-sqs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ssm:1.12.246-349.v96b_b_f7eb_a_c3c
aws-lambda:0.5.10
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-timeout:1.21
build-with-parameters:1.6
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-folder:6.729.v2b_9d1a_74d673
command-launcher:84.v4a_97f2027398
commons-lang3-api:3.12.0.0
commons-text-api:1.9-9.v39a_53e2e0343
conditional-buildstep:1.4.2
configuration-as-code:1462.v069a_b_57ff5c8
copyartifact:1.46.4
credentials:1129.vef26f5df883c
credentials-binding:523.vd859a_4b_122e6
custom-tools-plugin:0.8
dark-theme:185.v276b_5a_8966a_e
dashboard-view:2.432.va_712ce35862d
display-url-api:2.3.6
docker-commons:1.19
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-workflow:1.29
durable-task:496.va67c6f9eefa7
ec2:1.68
ec2-fleet:2.5.1
echarts-api:5.3.3-1
email-ext:2.89
emailext-template:1.4
extended-choice-parameter:346.vd87693c5a_86c
extensible-choice-parameter:1.8.0
extra-tool-installers:1.1
favorite:2.4.1
font-awesome-api:6.1.1-1
generic-webhook-trigger:1.84
git:4.11.3
git-client:3.11.0
git-parameter:0.9.17
git-server:1.11
gitlab-api:5.0.1-74.v44f46b_54c775
gitlab-branch-source:629.vb_cc76608e806
gitlab-plugin:1.5.34
greenballs:1.15.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hidden-parameter:0.0.5
htmlpublisher:1.30
http_request:1.15
jackson2-api:2.13.3-285.vc03c0256d517
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jersey2-api:2.36-2
job-dsl:1.79
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
kubernetes:3651.v908e7db_10d06
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
ldap:2.10
lockable-resources:2.15
logstash:2.5.0205.vd05825ed46bd
mailer:414.vcc4c33714601
matrix-auth:3.1.3
matrix-project:772.v494f19991984
maven-plugin:3.19
metrics:4.1.6.2
mina-sshd-api-common:2.8.0-21.v493b_6b_db_22c6
mina-sshd-api-core:2.8.0-21.v493b_6b_db_22c6
momentjs:1.1.1
node-iterator-api:1.5.1
pam-auth:1.8
parameterized-scheduler:1.0
parameterized-trigger:2.44
pipeline-aws:1.43
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:593.va_a_fc25d520e9
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2097.v33db_b_de764b_e
pipeline-model-definition:2.2097.v33db_b_de764b_e
pipeline-model-extensions:2.2097.v33db_b_de764b_e
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2097.v33db_b_de764b_e
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plugin-util-api:2.17.0
popper2-api:2.11.5-2
postbuildscript:3.1.0-375.v3db_cd92485e1
pyenv-pipeline:2.1.2
python:1.3
rebuild:1.34
resource-disposer:0.19
role-strategy:510.v909834359ec2
run-condition:1.5
s3:0.12.1
saml:2.298.vc7a_2b_3958628
scm-api:608.vfa_f971c5a_a_e9
script-security:1175.v4b_d517d6db_f0
slack:616.v03b_1e98d13dd
snakeyaml-api:1.30.1
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:277.v95c2fec1c047
ssh-slaves:1.821.vd834f8a_c390e
sshd:3.242.va_db_9da_b_26a_c3
strict-crumb-issuer:2.1.0
structs:318.va_f3ccb_729b_71
text-finder:1.19
theme-manager:1.4
throttle-concurrents:2.8
timestamper:1.18
token-macro:293.v283932a_0a_b_49
trilead-api:1.57.v6e90e07157e1
uno-choice:2.6.2
validating-string-parameter:2.8
variant:1.4
view-job-filters:2.3
windows-slaves:1.8.1
workflow-aggregator:581.v0c46fa_697ffd
workflow-api:1164.v760c223ddb_32
workflow-basic-steps:948.v2c72a_091b_b_68
workflow-cps:2725.v7b_c717eb_12ce
workflow-durable-task-step:1155.v79567b_e0a_2de
workflow-job:1189.va_d37a_e9e4eda_
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:820.vd1a_6cc65ef33
ws-cleanup:0.42
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04

### Reproduction steps

Upgraded my 2.332.4 Jenkins instance to 3.346.1.  Ran plugin updates.  Dark theme 185.v276b_5a_8966a_e pulled in Theme Manager 1.4.   Since this update I am unable to apply the dark theme, stays the white default theme.  Attempting to restart, log out/in, reset the theme in user configuration does not help.

### Expected Results

Dark theme.

### Actual Results

Theme now stuck at the default white theme, no matter what.

**Comment by timja** [comment] 2022-06-28 06:48
Duplicate of https://github.com/jenkinsci/dark-theme-plugin/issues/206 ?

**Comment by webminster** [comment] 2022-06-28 17:03
Certainly appears so, resetting the Jenkins URL does fix it.  Wasn't previously necessary.  Thanks.
-Alan

**Comment by timja** [comment] 2022-06-28 18:19
> Certainly appears so, resetting the Jenkins URL does fix it. Wasn't previously necessary. Thanks. -Alan

people keep asking me to change it to the other option -.-.
but either should work if you setup your config properly 😉

**Closed by timja** 2022-06-28 18:19 UTC
Labels: bug
